development:
  host: "localhost:3000"
  admin_email: "fguillen.mail@gmail.com"

  smtp:
    enabled: false

test:
  host: "test.com"
  admin_email: "rubio_de_marzo.mail@email.com"

  smtp:
    enabled: false

production:
  host: "rubiodemarzo.com"
  admin_email: "fguillen.mail@gmail.com"

  smtp:
    enabled: true
    server: "smtp.mandrillapp.com"
    port: 587
    domain: "rubiodemarzo.com"
    user_name: "fguillen"
    password: "<%= ENV.fetch('SMTP_PASS') %>"
